version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build Examples
          command: npm run build-examples

      - store_artifacts:
          path: build/examples
          destination: examples

      - run:
          name: Build API Docs
          command: npm run apidoc

      - store_artifacts:
          path: build/apidoc
          destination: apidoc
