name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
